-- =====================================================================
-- MULTI-TENANT — FASE 1 (segura de aplicar com o app atual no ar)
--
-- Cria `stores`, adiciona `store_id` (DEFAULT 1 = loja atual) em todas as
-- tabelas por-loja, troca as constraints UNIQUE globais por UNIQUE por loja
-- e cria triggers que impedem referência cruzada entre lojas.
--
-- Nada aqui muda o comportamento da loja atual: todas as linhas existentes
-- ficam com store_id = 1 e os INSERTs antigos (que não informam store_id)
-- continuam funcionando por causa do DEFAULT 1.
--
-- Rode a FASE 2 (2026-09-25_multi_tenant_phase2.sql) só depois que o código
-- passar store_id em toda query — ela remove o DEFAULT e liga o RLS.
--
-- Idempotente e transacional (tudo ou nada). Tabelas que não existirem no
-- seu banco (criadas sob demanda pelos ensure*()) são simplesmente puladas.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. Tabela raiz
-- ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS stores (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,                       -- subdomínio: <slug>.seudominio.com
  name TEXT NOT NULL,
  custom_domain TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'disabled')),
  suspended_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS stores_slug_key ON stores (lower(slug));
CREATE UNIQUE INDEX IF NOT EXISTS stores_custom_domain_key ON stores (lower(custom_domain)) WHERE custom_domain IS NOT NULL;

-- Loja atual = store 1 (ajuste o slug depois, se quiser).
INSERT INTO stores (id, slug, name) VALUES (1, 'principal', 'Loja principal') ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF to_regclass('public.store_settings') IS NOT NULL THEN
    UPDATE stores s SET
      name = COALESCE(NULLIF(ss.store_name, ''), s.name),
      status = CASE WHEN ss.suspended THEN 'suspended' ELSE s.status END,
      suspended_reason = ss.suspended_reason
    FROM (SELECT store_name, suspended, suspended_reason FROM store_settings ORDER BY id DESC LIMIT 1) ss
    WHERE s.id = 1;
  END IF;
END $$;

SELECT setval(pg_get_serial_sequence('stores', 'id'), GREATEST(1, (SELECT MAX(id) FROM stores)));

-- ---------------------------------------------------------------------
-- 2. Helpers temporários (somem no fim da sessão)
-- ---------------------------------------------------------------------

-- Derruba UNIQUE (constraint ou índice, não parcial) cujas colunas sejam EXATAMENTE `cols`.
CREATE FUNCTION pg_temp.drop_unique(tbl text, cols text[]) RETURNS void LANGUAGE plpgsql AS $$
DECLARE r record; rel regclass := to_regclass('public.' || tbl); want text;
BEGIN
  IF rel IS NULL THEN RETURN; END IF;
  SELECT string_agg(x, ',' ORDER BY x) INTO want FROM unnest(cols) x;
  FOR r IN
    SELECT c.conname FROM pg_constraint c
    WHERE c.conrelid = rel AND c.contype = 'u'
      AND (SELECT string_agg(a.attname::text, ',' ORDER BY a.attname)
           FROM unnest(c.conkey) k JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k) = want
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', rel, r.conname);
  END LOOP;
  FOR r IN
    SELECT i.indexrelid::regclass AS idx FROM pg_index i
    WHERE i.indrelid = rel AND i.indisunique AND NOT i.indisprimary
      AND i.indpred IS NULL AND i.indexprs IS NULL
      AND (SELECT string_agg(a.attname::text, ',' ORDER BY a.attname)
           FROM unnest(i.indkey::int2[]) k JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = k) = want
  LOOP
    EXECUTE format('DROP INDEX %s', r.idx);
  END LOOP;
END $$;

-- Troca a PK por `cols` (só age se a tabela JÁ tem PK e ela ainda não é `cols`).
CREATE FUNCTION pg_temp.set_pk(tbl text, cols text[]) RETURNS void LANGUAGE plpgsql AS $$
DECLARE rel regclass := to_regclass('public.' || tbl); pkname text; have text; want text;
BEGIN
  IF rel IS NULL THEN RETURN; END IF;
  SELECT c.conname,
         (SELECT string_agg(a.attname::text, ',' ORDER BY a.attname)
          FROM unnest(c.conkey) k JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k)
    INTO pkname, have
  FROM pg_constraint c WHERE c.conrelid = rel AND c.contype = 'p';
  IF pkname IS NULL THEN RETURN; END IF;
  SELECT string_agg(x, ',' ORDER BY x) INTO want FROM unnest(cols) x;
  IF have = want THEN RETURN; END IF;
  EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', rel, pkname);
  EXECUTE format('ALTER TABLE %s ADD PRIMARY KEY (%s)', rel, (SELECT string_agg(quote_ident(x), ',') FROM unnest(cols) x));
END $$;

-- Índice único (store_id) para tabelas "uma linha por loja"; avisa em vez de falhar se houver duplicatas.
CREATE FUNCTION pg_temp.unique_per_store(tbl text) RETURNS void LANGUAGE plpgsql AS $$
DECLARE n bigint;
BEGIN
  IF to_regclass('public.' || tbl) IS NULL THEN RETURN; END IF;
  EXECUTE format('SELECT COUNT(*) - COUNT(DISTINCT store_id) FROM %I', tbl) INTO n;
  IF n > 0 THEN
    RAISE NOTICE 'ATENÇÃO: % tem % linha(s) duplicada(s) por loja — UNIQUE(store_id) NÃO criado; limpe e rode de novo.', tbl, n;
  ELSE
    EXECUTE format('CREATE UNIQUE INDEX IF NOT EXISTS %I ON %I (store_id)', tbl || '_one_per_store', tbl);
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 3. store_id em todas as tabelas por-loja
-- ---------------------------------------------------------------------

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    -- identidade (clientes por loja) e equipe
    'users', 'discuser', 'googleuser', 'customer_profiles', 'email_codes', 'email_verification', 'logintoken',
    'admin', 'admin_roles', 'team_roles', 'team_base_permissions', 'team_audit_log',
    -- catálogo e configuração
    'categories', 'products', 'product_variations', 'product_images', 'stock_keys', 'coupons',
    'home_banners', 'store_settings', 'store_promotion_settings', 'carriers',
    'melhor_envio_credentials', 'mercadopago_credentials',
    -- vendas
    'orders', 'order_items', 'cart_items', 'payment_transactions', 'shipping_addresses',
    'shipments', 'shipment_events', 'shipping_quotes', 'stock_movements', 'delivery_failures',
    -- atendimento e engajamento
    'chat_conversations', 'chat_messages', 'chat_typing', 'notifications',
    'product_questions', 'product_question_messages', 'product_reviews', 'page_views',
    -- revenda
    'resellers', 'reseller_products', 'reseller_commissions', 'reseller_payout_requests'
  ] LOOP
    IF to_regclass('public.' || t) IS NOT NULL THEN
      EXECUTE format('ALTER TABLE %I ADD COLUMN IF NOT EXISTS store_id INTEGER NOT NULL DEFAULT 1 REFERENCES stores(id) ON DELETE RESTRICT', t);
      EXECUTE format('CREATE INDEX IF NOT EXISTS %I ON %I (store_id)', t || '_store_idx', t);
    ELSE
      RAISE NOTICE 'tabela % não existe neste banco — pulada', t;
    END IF;
  END LOOP;
END $$;

-- ---------------------------------------------------------------------
-- 4. UNIQUEs globais -> UNIQUEs por loja
-- ---------------------------------------------------------------------

-- 4.1 users.email (customer_profiles referencia users(email): recria a FK composta)
DO $$
DECLARE r record;
BEGIN
  IF to_regclass('public.customer_profiles') IS NOT NULL AND to_regclass('public.users') IS NOT NULL THEN
    FOR r IN SELECT conname FROM pg_constraint
             WHERE conrelid = 'public.customer_profiles'::regclass AND contype = 'f' AND confrelid = 'public.users'::regclass
    LOOP
      EXECUTE format('ALTER TABLE customer_profiles DROP CONSTRAINT %I', r.conname);
    END LOOP;
  END IF;
END $$;

SELECT pg_temp.drop_unique('users', ARRAY['email']);
CREATE UNIQUE INDEX IF NOT EXISTS users_store_email_key ON users (store_id, email);

SELECT pg_temp.set_pk('customer_profiles', ARRAY['store_id', 'email']);
DO $$
BEGIN
  IF to_regclass('public.customer_profiles') IS NOT NULL
     AND NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'customer_profiles_user_fk') THEN
    ALTER TABLE customer_profiles
      ADD CONSTRAINT customer_profiles_user_fk
      FOREIGN KEY (store_id, email) REFERENCES users (store_id, email) ON DELETE CASCADE;
  END IF;
END $$;

-- 4.2 contas sociais e códigos de login
SELECT pg_temp.drop_unique('discuser', ARRAY['email']);
CREATE UNIQUE INDEX IF NOT EXISTS discuser_store_email_key ON discuser (store_id, email);
SELECT pg_temp.drop_unique('googleuser', ARRAY['email']);
CREATE UNIQUE INDEX IF NOT EXISTS googleuser_store_email_key ON googleuser (store_id, email);
SELECT pg_temp.set_pk('email_codes', ARRAY['store_id', 'email']);

-- 4.3 equipe (admin.email hoje nem é único; a mesma pessoa pode ser staff de várias lojas)
SELECT pg_temp.drop_unique('admin', ARRAY['email']);
CREATE UNIQUE INDEX IF NOT EXISTS admin_store_email_key ON admin (store_id, email);
SELECT pg_temp.drop_unique('team_roles', ARRAY['name']);
CREATE UNIQUE INDEX IF NOT EXISTS team_roles_store_name_key ON team_roles (store_id, name);
SELECT pg_temp.set_pk('team_base_permissions', ARRAY['store_id', 'role']);

-- 4.4 catálogo
SELECT pg_temp.drop_unique('categories', ARRAY['slug']);
CREATE UNIQUE INDEX IF NOT EXISTS categories_store_slug_key ON categories (store_id, slug);
SELECT pg_temp.drop_unique('products', ARRAY['slug']);
CREATE UNIQUE INDEX IF NOT EXISTS products_store_slug_key ON products (store_id, slug);
SELECT pg_temp.drop_unique('coupons', ARRAY['code']);
CREATE UNIQUE INDEX IF NOT EXISTS coupons_store_code_key ON coupons (store_id, code);

-- 4.5 revenda e transportadoras
SELECT pg_temp.drop_unique('resellers', ARRAY['referral_code']);
CREATE UNIQUE INDEX IF NOT EXISTS resellers_store_referral_key ON resellers (store_id, referral_code);

DROP INDEX IF EXISTS carriers_melhor_envio_service_id_idx;
CREATE UNIQUE INDEX IF NOT EXISTS carriers_store_melhor_envio_idx
  ON carriers (store_id, melhor_envio_service_id) WHERE melhor_envio_service_id IS NOT NULL;

-- 4.6 configurações: uma linha por loja
-- store_settings acumulou linhas antigas (o app só lê a mais recente:
-- ORDER BY id DESC LIMIT 1). Guarda as antigas numa tabela de backup e mantém
-- só a mais recente por loja, para poder criar o UNIQUE(store_id).
DO $$
BEGIN
  IF to_regclass('public.store_settings') IS NOT NULL THEN
    CREATE TABLE IF NOT EXISTS store_settings_old_rows AS SELECT * FROM store_settings WHERE false;
    INSERT INTO store_settings_old_rows
      SELECT * FROM store_settings s
      WHERE s.id <> (SELECT MAX(id) FROM store_settings x WHERE x.store_id = s.store_id)
        AND NOT EXISTS (SELECT 1 FROM store_settings_old_rows o WHERE o.id = s.id);
    DELETE FROM store_settings s
      WHERE s.id <> (SELECT MAX(id) FROM store_settings x WHERE x.store_id = s.store_id);
  END IF;
END $$;
SELECT pg_temp.unique_per_store('store_settings');
SELECT pg_temp.unique_per_store('store_promotion_settings');
SELECT pg_temp.unique_per_store('melhor_envio_credentials');
SELECT pg_temp.unique_per_store('mercadopago_credentials');

-- Mantidos globais de propósito (identificadores externos/aleatórios):
--   orders.payment_ref, orders.order_number (12 chars aleatórios),
--   payment_transactions(provider, provider_txid) e idempotency_key.

-- ---------------------------------------------------------------------
-- 5. Impede referência cruzada entre lojas (filho.store_id = pai.store_id)
-- ---------------------------------------------------------------------

CREATE OR REPLACE FUNCTION enforce_same_store() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE fk_val bigint; parent_store integer;
BEGIN
  EXECUTE format('SELECT ($1).%I', TG_ARGV[0]) INTO fk_val USING NEW;
  IF fk_val IS NULL THEN RETURN NEW; END IF;
  EXECUTE format('SELECT store_id FROM %I WHERE id = $1', TG_ARGV[1]) INTO parent_store USING fk_val;
  IF parent_store IS NOT NULL AND parent_store <> NEW.store_id THEN
    RAISE EXCEPTION 'cross-tenant reference: %.% (store %) -> %.id (store %)',
      TG_TABLE_NAME, TG_ARGV[0], NEW.store_id, TG_ARGV[1], parent_store
      USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END $$;

DO $$
DECLARE r record;
BEGIN
  FOR r IN SELECT * FROM (VALUES
    ('products', 'category_id', 'categories'),
    ('product_variations', 'product_id', 'products'),
    ('product_images', 'product_id', 'products'),
    ('stock_keys', 'product_id', 'products'),
    ('stock_keys', 'variation_id', 'product_variations'),
    ('stock_keys', 'order_id', 'orders'),
    ('orders', 'user_id', 'users'),
    ('orders', 'coupon_id', 'coupons'),
    ('orders', 'reseller_id', 'resellers'),
    ('orders', 'shipping_address_id', 'shipping_addresses'),
    ('order_items', 'order_id', 'orders'),
    ('order_items', 'product_id', 'products'),
    ('order_items', 'variation_id', 'product_variations'),
    ('cart_items', 'user_id', 'users'),
    ('cart_items', 'product_id', 'products'),
    ('cart_items', 'variation_id', 'product_variations'),
    ('shipping_addresses', 'user_id', 'users'),
    ('shipments', 'order_id', 'orders'),
    ('shipments', 'carrier_id', 'carriers'),
    ('shipment_events', 'shipment_id', 'shipments'),
    ('shipping_quotes', 'order_id', 'orders'),
    ('shipping_quotes', 'carrier_id', 'carriers'),
    ('payment_transactions', 'order_id', 'orders'),
    ('stock_movements', 'order_id', 'orders'),
    ('delivery_failures', 'order_id', 'orders'),
    ('chat_conversations', 'order_id', 'orders'),
    ('chat_messages', 'conversation_id', 'chat_conversations'),
    ('notifications', 'user_id', 'users'),
    ('product_questions', 'product_id', 'products'),
    ('product_questions', 'user_id', 'users'),
    ('product_question_messages', 'question_id', 'product_questions'),
    ('product_reviews', 'product_id', 'products'),
    ('product_reviews', 'user_id', 'users'),
    ('resellers', 'user_id', 'users'),
    ('reseller_products', 'reseller_id', 'resellers'),
    ('reseller_products', 'product_id', 'products'),
    ('reseller_commissions', 'reseller_id', 'resellers'),
    ('reseller_commissions', 'order_id', 'orders'),
    ('reseller_commissions', 'product_id', 'products'),
    ('reseller_payout_requests', 'reseller_id', 'resellers'),
    ('admin_roles', 'admin_id', 'admin'),
    ('admin_roles', 'role_id', 'team_roles'),
    ('logintoken', 'user_id', 'users'),
    ('discuser', 'user_id', 'users'),
    ('googleuser', 'user_id', 'users')
  ) AS v(child, col, parent)
  LOOP
    IF to_regclass('public.' || r.child) IS NOT NULL
       AND to_regclass('public.' || r.parent) IS NOT NULL
       AND EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public' AND table_name = r.child AND column_name = r.col)
    THEN
      IF EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'trg_same_store_' || r.col AND tgrelid = to_regclass('public.' || r.child)) THEN
        EXECUTE format('DROP TRIGGER %I ON %I', 'trg_same_store_' || r.col, r.child);
      END IF;
      EXECUTE format(
        'CREATE TRIGGER %I BEFORE INSERT OR UPDATE OF %I, store_id ON %I FOR EACH ROW EXECUTE FUNCTION enforce_same_store(%L, %L)',
        'trg_same_store_' || r.col, r.col, r.child, r.col, r.parent);
    END IF;
  END LOOP;
END $$;

COMMIT;
